import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

typedef SharedPreferencesLoader = Future<SharedPreferences> Function();

class LanguageProvider extends ChangeNotifier {
  LanguageProvider({SharedPreferencesLoader? preferencesLoader})
    : _preferencesLoader = preferencesLoader ?? SharedPreferences.getInstance {
    _loadSavedLanguage();
  }

  static const String _storageKey = 'app_language_code';
  static const List<Locale> supportedLocales = [Locale('en'), Locale('sw')];

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'dashboard': 'Dashboard',
      'search': 'Search',
      'users': 'Users',
      'training': 'training',
      'applications': 'Applications',
      'home': 'Home',
      'apps': 'Apps',
      'browse': 'Browse',
      'my_apps': 'My Apps',
      'my_training': 'My training',
      'profile': 'Profile',
      'settings': 'Settings',
      'change_language': 'Change language',
      'change_language_title': 'Change Language',
      'language': 'Language',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'apply': 'Apply',
      'notifications': 'Notifications',
      'admin_settings': 'Admin Settings',
      'student_settings': 'Student Settings',
      'organization_settings': 'Organization Settings',
      'open_admin_notifications': 'Open admin notifications',
      'open_your_notifications': 'Open your notifications',
      'open_organization_notifications': 'Open organization notifications',
      'refresh_unread_count': 'Refresh unread count',
      'sync_latest_notification_badge': 'Sync the latest notification badge',
      'my_applications': 'My Applications',
      'open_applications_tab': 'Open applications tab',
      'organization_profile': 'Organization Profile',
      'open_profile_tab': 'Open profile tab',
      'logout_title': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'logout_success': 'Logout successful!',
      'language_changed_to': 'Language changed to {language}',
      'admin_panel_date': 'Admin Panel • {date}',
      'organization_dashboard': 'Organization Dashboard',
      'government_system': 'Government System',
      'more_actions': 'More actions',
      'hello_name': 'Hello, {name}!',
      'student': 'Student',
      'organization': 'Organization',
      'search_organization_training_hint': 'Search organization or training',
      'search_admin_subtitle':
          'Find organization and training quickly from one place.',
      'search_organization': 'Organization',
      'search_training': 'training',
      'open_users_tab': 'Open users tab',
      'open_training_tab': 'Open training tab',
      'start_search_message':
          'Start typing to search for a organization or a job.',
      'no_search_results': 'No matching organization or training found.',
      'search_results_count': '{count} result(s)',
      'industry_label': 'Industry: {value}',
      'location_label': 'Location: {value}',
      'email_label': 'Email: {value}',
      'organization_label': 'Organization: {value}',
      'report': 'Report',
      'admin': 'Admin',
      '': 'Industrial Practical Training',
      'welcome_name': 'Welcome, {name}',
      'welcome_back_name': 'Welcome back, {name}',
      'admin_profile': 'Admin profile',
      'refresh_counters': 'Refresh counters',
      'login': 'Login',
      'login_success': 'Login successful!',
      'login_failed_check_credentials': 'Login failed. Check your credentials.',
      'reset_email_sent':
          'If an account with that email exists, a reset link has been sent.',
      'reset_email_resent':
          'If an account with that email exists, the reset link has been sent again.',
      'resend': 'Resend',
      'reset_now': 'Reset Now',
      'reset_link_ready': 'Reset Link Ready',
      'reset_link_ready_body':
          'If your email app does not open the link,   open the reset screen and paste it there.',
      'reset_link_copied': 'Reset link copied',
      'copy_reset_link': 'Copy reset link',
      'open_reset_screen': 'Open reset screen',
      'united_republic_of_tanzania': 'THE UNITED REPUBLIC OF TANZANIA',
      'internship_government_system': 'INDUSTRIAL PRACTICAL TRAINING SYSTEM',
      'empowering_tanzanian_youth': 'Empowering youth of Tanzania',
      'email_or_username': 'Email',
      'enter_your_email_address': 'Enter your email address',
      'please_enter_your_email': 'Please enter your email',
      'enter_valid_email_address': 'Enter a valid email address',
      'password': 'Password',
      'please_enter_your_password': 'Please enter your password',
      'password_min_6': 'Password must be at least 6 characters',
      'forgot_password': 'Forgot Password',
      //'forgot_password_prompt': 'Tap here to get a reset link by email',
      'dont_have_account': "Don't have an account?",
      'developed_by_name': 'Developed by {name}',
      'version_value': 'Version {value}',
      'logging_in': 'Logging in...',
      'forgot_password_description':
          'Enter your email address and we will send you a secure reset link.',
      'email_address': 'Email address',
      'sending': 'Sending...',
      'send_link': 'Send Link',
      'failed_send_password_reset_link': 'Failed to send password reset link',
      'create_account': 'Create Account',
      'create_new_account': 'Create New Account',
      'choose_account_type': 'Choose Account Type',
      'choose_account_type_subtitle':
          'Select how you want to register on the platform.',
      'student_register_option':
          'Register as a student to apply for practical training opportunities.',
      'organization_register_option':
          'Register as a organization to post opportunities and manage applicants.',
      'university_register_option':
          'Register as a university or college and manage institution details.',
      'other_institution': ' Institution',
      'institution_register_option':
          'Register as a government office or public institution and coordinate placements.',
      'change_account_type': 'Change account type',
      'basic_information': 'Basic Information',
      'student_details': 'Student Details',
      'organization_details': 'Organization Details',
      'university_details': 'University Details',
      'institution_details': 'Institution Details',
      'student_registration_subtitle': '',
      'organization_registration_subtitle':
          'Fill in your organization information to create an employer account.',
      'university_registration_subtitle': '',
      'institution_registration_subtitle':
          'Fill in government office details to create an institution account.',
      'university_registration_coming':
          'University registration is now available.',
      'college_information': 'College Information',
      'government_office_information': 'Government Office Information',
      'coordinator_information': 'Coordinator Information',
      'account_security': 'Account Security',
      'continue': 'Continue',
      'please_check_information_try_again':
          'Please check your information and try again.',
      'registration_successful': 'Registration Successful!',
      'welcome_to_government_internship_system':
          'Welcome to Industrial Practical Training System',
      'registration_failed': 'Registration Failed',
      'try_again': 'Try Again',
      'loading_universities': 'Loading universities...',
      'loading_': 'Loading ...',
      'i_am_a': 'I am a:',
      'first_name': 'First Name',
      'first_name_required': 'First name is required',
      'first_name_min_2': 'First name must be at least 2 characters',
      'second_name': 'Second Name',
      'second_name_required': 'Second name is required',
      'second_name_min_2': 'Second name must be at least 2 characters',
      'full_name': 'Full Name',
      'full_name_required': 'Full name is required',
      'full_name_min_3': 'Full name must be at least 3 characters',
      'email': 'Email',
      'email_required': 'Email is required',
      'email_must_contain_at': 'Email must contain @',
      'email_must_contain_domain':
          'Email must contain domain (e.g., .com, .ac.tz)',
      'phone_number': 'Phone Number',
      'phone_hint_tz': 'e.g., 0712345678 or +255712345678',
      'phone_number_required': 'Phone number is required',
      'enter_valid_tanzanian_phone':
          'Enter valid Tanzanian phone (e.g., 0712345678 or +255712345678)',
      'password_helper': '',
      'password_required': 'Password is required',
      'password_min_8': 'Password must be at least 8 characters',
      'password_uppercase_required':
          'Password must contain at least one uppercase letter',
      'password_lowercase_required':
          'Password must contain at least one lowercase letter',
      'password_number_required': 'Password must contain at least one number',
      'confirm_password': 'Confirm Password',
      'please_confirm_password': 'Please confirm your password',
      'passwords_do_not_match': 'Passwords do not match',
      'university': 'University',
      'government_office': 'Government Office',
      'retry_loading_universities': 'Retry loading universities',
      'select_your_university': 'Select your university',
      'tap_refresh_to_load_universities': ' load universities',
      'universities_unavailable_refresh':
          'Universities unavailable. Tap refresh icon.',
      'no_universities_available_right_now':
          'No universities available right now',
      'please_select_university': 'Please select a university',
      'institution': 'Institution',
      'search_institution': 'Search institution',
      'retry_loading_': 'Retry loading ',
      '_unavailable_refresh': ' unavailable. Tap refresh icon.',
      'no__available_right_now': 'No  available right now',
      'please_select_institution': 'Please select an institution',
      'please_select_institution_from_list':
          'Please select an institution from the list',
      'loading_government_offices': 'Loading government offices...',
      'retry_loading_government_offices': 'Retry loading government offices',
      'select_government_office': 'Select a government office',
      'tap_refresh_to_load_government_offices':
          'Tap refresh to load government offices',
      'government_offices_unavailable_refresh':
          'Government offices unavailable. Tap refresh icon.',
      'no_government_offices_available_right_now':
          'No government offices available right now',
      'please_select_government_office': 'Please select a government office',
      'program_course': 'Program / Course',
      'program_required': 'Program is required',
      'registration_number': 'Registration Number',
      'registration_number_required': 'Registration number is required',
      'identification_card': 'Identification Card',
      'upload_identification_card': 'Upload Identification Card',
      'upload_identification_hint':
          'Upload a clear PDF copy of your ID card. Maximum 5MB.',
      'upload_identification_required':
          'Please upload your identification card before continuing.',
      'university_name': 'University Name',
      'university_name_required': 'University name is required',
      'college_name': 'College Name',
      'college_name_required': 'College name is required',
      'institution_name': 'Institution Name',
      'institution_name_required': 'Institution name is required',
      'college_reg_no': 'College Registration Number',
      'college_reg_no_required': 'College registration number is required',
      'institution_reg_no': 'Institution Registration Number',
      'institution_reg_no_required':
          'Institution registration number is required',
      'college_email': 'College Email',
      'college_email_required': 'College email is required',
      'institution_email': 'Institution Email',
      'institution_email_required': 'Institution email is required',
      'college_phone': 'College Phone',
      'college_phone_required': 'College phone is required',
      'institution_phone': 'Institution Phone',
      'institution_phone_required': 'Institution phone is required',
      'college_address': 'College Address',
      'college_address_required': 'College address is required',
      'institution_address': 'Institution Address',
      'institution_address_required': 'Institution address is required',
      'college_region': 'College Region',
      'college_region_required': 'College region is required',
      'institution_region': 'Institution Region',
      'institution_region_required': 'Institution region is required',
      'select_college_region': 'Select college region',
      'college_district': 'College District',
      'college_district_required': 'College district is required',
      'institution_district': 'Institution District',
      'institution_district_required': 'Institution district is required',
      'select_college_district': 'Select college district',
      'select_region_first': 'Select region first',
      'college_website': 'College Website',
      'institution_website': 'Institution Website',
      'college_logo': 'College Logo',
      'upload_college_logo': 'Upload College Logo',
      'upload_college_logo_hint':
          'Upload a clear JPG, JPEG, or PNG logo for the college. Maximum 5MB.',
      'upload_college_logo_required':
          'Please upload the college logo before continuing.',
      'institution_logo': 'Institution Logo',
      'upload_institution_logo': 'Upload Institution Logo',
      'upload_institution_logo_hint':
          'Upload a clear JPG, JPEG, or PNG logo for the institution. Maximum 5MB.',
      'upload_institution_logo_required':
          'Please upload the institution logo before continuing.',
      'college_type': 'College Type',
      'college_type_required': 'Please select the college type',
      'institution_type': 'Institution Type',
      'institution_type_required': 'Please select the institution type',
      'coordinator_name': 'Coordinator Name',
      'coordinator_name_required': 'Coordinator name is required',
      'coordinator_phone': 'Coordinator Phone',
      'coordinator_phone_required': 'Coordinator phone is required',
      'coordinator_email': 'Coordinator Email',
      'coordinator_email_required': 'Coordinator email is required',
      'coming_soon': 'Coming Soon',
      'student_type': 'Student Type:',
      'current_student': 'Current Student',
      'expected_graduation_year': 'Expected Graduation Year',
      'please_select_graduation_year': 'Please select graduation year',
      '_type': 'Training Type:',
      'graduation_year': 'Graduation Year',
      'experience_level': 'Experience Level',
      'no_experience': 'No Experience',
      'experience_0_1_year': '0-1 Year',
      'experience_1_2_years': '1-2 Years',
      'experience_2_3_years': '2-3 Years',
      'experience_3_plus_years': '3+ Years',
      'please_select_experience_level': 'Please select experience level',
      'organization_name': 'Organization Name',
      'organization_name_required': 'Organization name is required',
      'search_organization_name': 'Search organization name',
      'retry_loading_organization_directory':
          'Retry loading organization directory',
      'industry': 'Industry',
      'please_select_industry': 'Please select industry',
      'organization_size': 'Organization Size',
      'employees_count': '{size} employees',
      'please_select_organization_size': 'Please select organization size',
      'location': 'Location',
      'location_required': 'Location is required',
      'organization_description': 'Organization Description',
      'register': 'Register',
      'already_have_account': 'Already have an account?',
      'website': 'Website',
      'phone': 'Phone',
      'not_provided': 'Not provided',
      'industry_not_set': 'Industry not set',
      'edit_profile': 'Edit Profile',
      'edit_job': 'Edit Job',
      'edit_training': 'Edit Training',
      'no_organization_description_added_yet':
          'No organization description added yet.',
      'no_deadline': 'No deadline',
      'expired': 'Expired',
      'days_left': '{count} days left',
      'closes_today': 'Closes today',
      'invalid_date': 'Invalid date',
      'status_active': 'Active',
      'status_closed': 'Closed',
      'salary': 'Salary',
      'job_type': 'Job Type',
      'applicants_count': '{count} applicants',
      'needed_count': '{count} needed',
      'deadline': 'Deadline',
      'no_description_provided': 'No description provided',
      'target_candidates': 'Target Candidates',
      'first_year': 'First Year',
      'second_year': 'Second Year',
      'third_year_plus': '3 Year+',
      'organization_statistics': 'Organization Statistics',
      'total_training': 'Total training',
      'active_training': 'Active training',
      'closed_training': 'Closed training',
      'total_applicants': 'Total Applicants',
      'average_per_training': 'Average per Training',
      'average_per_job': 'Average per Job',
      'welcome_back': 'Welcome back,',
      'quick_actions': 'Quick Actions',
      'post_training': 'Post Training',
      'post_job': 'Post Job',
      'view_training': 'View training',
      'find_talent': 'Find Talent',
      'find_talent_coming_soon': 'Find Talent feature coming soon!',
      'statistics': 'Statistics',
      'recent_job_postings': 'Recent practical  Postings',
      'recent_training_postings': 'Recent practical  Postings',
      'view_all': 'View All',
      'no_training_posted_yet': 'No prctical taraing  posted yet',
      'click_create_first_job': 'Click + to create your first job',
      'details': 'Details',
      'failed_to_load_training': 'Failed to load practical traing ',
      'untitled_job': 'Untitled Job',
      'untitled_training': 'Untitled Training',
      'location_not_specified': 'Location not specified',
      'all_applications': 'All Applications',
      'this_job': 'This Job',
      'all_organization_applications': 'All Organization Applications',
      'applications_for_job': 'Applications for {job}',
      'network_error': 'Network error',
      'failed_to_load_applications': 'Failed to load applications',
      'select_reporting_start_date': 'Select reporting start date',
      'select_reporting_end_date': 'Select reporting end date',
      'application_updated_to': 'Application updated to {status}',
      'failed_to_update_status': 'Failed to update status',
      'applications_summary': 'Applications Summary',
      'total': 'Total',
      'shortlisted': 'Shortlisted',
      'ed': 'ed',
      'accepted': 'Accepted',
      'rejected': 'Rejected',
      'unknown_applicant': 'Unknown Applicant',
      'no_email': 'No email',
      'selected_job': 'Selected Job',
      'selected_training': 'Selected Training',
      'university_value': 'University: {value}',
      'job_value': 'Job: {value}',
      'training_value': 'Training: {value}',
      'shortlist': 'Shortlist',
      'interview': 'Interview',
      'accept': 'Accept',
      'reject': 'Reject',
      'go_to_my_training': 'Go to My training',
      'no_applications_for_training_yet':
          'No applications for your training yet',
      'no_applications_for_this_job_yet': 'No applications for this job yet',
      'no_applications_for_this_training_yet':
          'No applications for this training yet',
      'close': 'Close',
      '_venue': ' Venue',
      'venue_required': 'Venue is required',
      'venue_hall': 'Venue / Hall',
      'venue_hint': 'Example: Main Hall, Room 4',
      'status_pending': 'Pending',
      'status_shortlisted': 'Shortlisted',
      'status_': '',
      'status_accepted': 'Accepted',
      'status_rejected': 'Rejected',
    },
    'sw': {
      'dashboard': 'Dashibodi',
      'search': 'Tafuta',
      'users': 'Watumiaji',
      'training': 'Kazi',
      'applications': 'Maombi',
      'home': 'Nyumbani',
      'apps': 'Appu',
      'browse': 'Tafuta',
      'my_apps': 'Maombi Yangu',
      'my_training': 'Kazi Zangu',
      'profile': 'Wasifu',
      'settings': 'Mipangilio',
      'change_language': 'Badili lugha',
      'change_language_title': 'Badili Lugha',
      'language': 'Lugha',
      'logout': 'Toka',
      'cancel': 'Ghairi',
      'apply': 'Tumia',
      'notifications': 'Arifa',
      'admin_settings': 'Mipangilio ya Admin',
      'student_settings': 'Mipangilio ya Mwanafunzi',
      'organization_settings': 'Mipangilio ya Kampuni',
      'open_admin_notifications': 'Fungua arifa za admin',
      'open_your_notifications': 'Fungua arifa zako',
      'open_organization_notifications': 'Fungua arifa za kampuni',
      'refresh_unread_count': 'Sasisha idadi ya arifa',
      'sync_latest_notification_badge': 'Leta alama ya arifa mpya',
      'my_applications': 'Maombi Yangu',
      'open_applications_tab': 'Fungua ukurasa wa maombi',
      'organization_profile': 'Wasifu wa Kampuni',
      'open_profile_tab': 'Fungua ukurasa wa wasifu',
      'logout_title': 'Toka',
      'logout_confirm': 'Una uhakika unataka kutoka?',
      'logout_success': 'Umetoka kwa mafanikio!',
      'language_changed_to': 'Lugha imebadilishwa kuwa {language}',
      'admin_panel_date': 'Paneli ya Admin • {date}',
      'organization_dashboard': 'Dashibodi ya Kampuni',
      'government_system': 'Mfumo wa Serikali',
      'more_actions': 'Vitendo zaidi',
      'hello_name': 'Habari, {name}!',
      'student': 'Mwanafunzi',
      'organization': 'Kampuni',
      'search_organization_training_hint': 'Tafuta kampuni au kazi',
      'search_admin_subtitle':
          'Pata kampuni na kazi kwa haraka kutoka sehemu moja.',
      'search_organization': 'Kampuni',
      'search_training': 'Kazi',
      'open_users_tab': 'Fungua ukurasa wa watumiaji',
      'open_training_tab': 'Fungua ukurasa wa kazi',
      'start_search_message': 'Anza kuandika kutafuta kampuni au kazi.',
      'no_search_results': 'Hakuna kampuni au kazi iliyopatikana.',
      'search_results_count': 'Matokeo {count}',
      'industry_label': 'Sekta: {value}',
      'location_label': 'Mahali: {value}',
      'email_label': 'Barua pepe: {value}',
      'organization_label': 'Kampuni: {value}',
      'report': 'Ripoti',
      'admin': 'Admin',
      '': 'Mafunzo kwa Vitendo Viwandani',
      'welcome_name': 'Karibu, {name}',
      'welcome_back_name': 'Karibu tena, {name}',
      'admin_profile': 'Wasifu wa admin',
      'refresh_counters': 'Sasisha vihesabu',
      'login': 'Ingia',
      'login_success': 'Umeingia kwa mafanikio!',
      'login_failed_check_credentials':
          'Imeshindikana kuingia. Angalia taarifa zako.',
      'reset_email_sent':
          'Kama akaunti yenye barua pepe hiyo ipo, link ya kurejesha nenosiri imetumwa.',
      'reset_email_resent':
          'Kama akaunti yenye barua pepe hiyo ipo, link ya kurejesha nenosiri imetumwa tena.',
      'resend': 'Tuma tena',
      'reset_now': 'Weka upya sasa',
      'reset_link_ready': 'Link ya kuweka upya iko tayari',
      'reset_link_ready_body':
          'Ikiwa app ya email haifungui link, nakili link hii au fungua ukurasa wa kuweka upya na uibandike huko.',
      'reset_link_copied': 'Link ya kuweka upya imenakiliwa',
      'copy_reset_link': 'Nakili link ya kuweka upya',
      'open_reset_screen': 'Fungua ukurasa wa kuweka upya',
      'united_republic_of_tanzania': 'JAMHURI YA MUUNGANO WA TANZANIA',
      'internship_government_system':
          'MFUMO WA SERIKALI WA MAFUNZO KWA VITENDO VIWANDANI',
      'empowering_tanzanian_youth': 'Kuwawezesha vijana wa Tanzania',
      'email_or_username': 'Barua pepe',
      'enter_your_email_address': 'Weka anuani yako ya barua pepe',
      'please_enter_your_email': 'Tafadhali weka barua pepe yako',
      'enter_valid_email_address': 'Weka barua pepe sahihi',
      'password': 'Nenosiri',
      'please_enter_your_password': 'Tafadhali weka nenosiri lako',
      'password_min_6': 'Nenosiri lazima liwe na angalau herufi 6',
      'forgot_password': 'Umesahau nenosiri',
      'forgot_password_prompt':
          'Bonyeza hapa kupata link ya kurejesha kwa email',
      'dont_have_account': 'Huna akaunti?',
      'developed_by_name': 'Imetengenezwa na {name}',
      'version_value': 'Toleo {value}',
      'logging_in': 'Inaingia...',
      'forgot_password_description':
          'Weka barua pepe yako na tutakutumia link salama ya kuweka upya.',
      'email_address': 'Anuani ya barua pepe',
      'sending': 'Inatuma...',
      'send_link': 'Tuma link',
      'failed_send_password_reset_link':
          'Imeshindikana kutuma link ya kuweka upya nenosiri',
      'create_account': 'Fungua Akaunti',
      'create_new_account': 'Fungua Akaunti Mpya',
      'choose_account_type': 'Chagua Aina ya Akaunti',
      'choose_account_type_subtitle':
          'Chagua namna unavyotaka kujisajili kwenye mfumo.',
      'student_register_option':
          'Jisajili kama mwanafunzi kuomba nafasi za mafunzo kwa vitendo.',
      'organization_register_option':
          'Jisajili kama kampuni kutangaza nafasi na kusimamia waombaji.',
      'university_register_option':
          'Jisajili kama chuo na simamia taarifa za taasisi.',
      'other_institution': 'Taasisi Nyingine',
      'institution_register_option':
          'Jisajili kama ofisi ya serikali au taasisi ya umma kusimamia nafasi za mafunzo.',
      'change_account_type': 'Badili aina ya akaunti',
      'basic_information': 'Taarifa za Msingi',
      'student_details': 'Taarifa za Mwanafunzi',
      'organization_details': 'Taarifa za Kampuni',
      'university_details': 'Taarifa za Chuo',
      'institution_details': 'Taarifa za Taasisi',
      'student_registration_subtitle':
          'Jaza taarifa za mwanafunzi na pakia kitambulisho chako.',
      'organization_registration_subtitle':
          'Jaza taarifa za kampuni ili kufungua akaunti ya mwajiri.',
      'university_registration_subtitle':
          'Jaza taarifa za taasisi ili kufungua akaunti ya chuo.',
      'institution_registration_subtitle':
          'Jaza taarifa za ofisi ya serikali ili kufungua akaunti ya taasisi.',
      'university_registration_coming': 'Usajili wa chuo sasa unapatikana.',
      'college_information': 'Taarifa za Chuo',
      'government_office_information': 'Taarifa za Ofisi ya Serikali',
      'coordinator_information': 'Taarifa za Mratibu',
      'account_security': 'Usalama wa Akaunti',
      'continue': 'Endelea',
      'please_check_information_try_again':
          'Tafadhali angalia taarifa zako kisha ujaribu tena.',
      'registration_successful': 'Usajili umefanikiwa!',
      'welcome_to_government_internship_system':
          'Karibu kwenye Mfumo wa Mafunzo kwa Vitendo Viwandani',
      'registration_failed': 'Usajili umeshindikana',
      'try_again': 'Jaribu tena',
      'loading_universities': 'Inapakia vyuo vikuu...',
      'loading_': 'Inapakia taasisi...',
      'i_am_a': 'Mimi ni:',
      'first_name': 'Jina la kwanza',
      'first_name_required': 'Jina la kwanza linahitajika',
      'first_name_min_2': 'Jina la kwanza lazima liwe na angalau herufi 2',
      'second_name': 'Jina la pili',
      'second_name_required': 'Jina la pili linahitajika',
      'second_name_min_2': 'Jina la pili lazima liwe na angalau herufi 2',
      'full_name': 'Jina kamili',
      'full_name_required': 'Jina kamili linahitajika',
      'full_name_min_3': 'Jina kamili lazima liwe na angalau herufi 3',
      'email': 'Barua pepe',
      'email_required': 'Barua pepe inahitajika',
      'email_must_contain_at': 'Barua pepe lazima iwe na @',
      'email_must_contain_domain':
          'Barua pepe lazima iwe na domain, kama .com au .ac.tz',
      'phone_number': 'Namba ya simu',
      'phone_hint_tz': 'mfano, 0712345678 au +255712345678',
      'phone_number_required': 'Namba ya simu inahitajika',
      'enter_valid_tanzanian_phone':
          'Weka namba sahihi ya Tanzania, kama 0712345678 au +255712345678',
      'password_helper':
          'Angalau herufi 8, herufi kubwa 1, ndogo 1, na namba 1',
      'password_required': 'Nenosiri linahitajika',
      'password_min_8': 'Nenosiri lazima liwe na angalau herufi 8',
      'password_uppercase_required':
          'Nenosiri lazima liwe na angalau herufi kubwa moja',
      'password_lowercase_required':
          'Nenosiri lazima liwe na angalau herufi ndogo moja',
      'password_number_required': 'Nenosiri lazima liwe na angalau namba moja',
      'confirm_password': 'Thibitisha nenosiri',
      'please_confirm_password': 'Tafadhali thibitisha nenosiri lako',
      'passwords_do_not_match': 'Nywila haziendani',
      'university': 'Chuo kikuu',
      'government_office': 'Ofisi ya Serikali',
      'retry_loading_universities': 'Jaribu tena kupakia vyuo vikuu',
      'select_your_university': 'Chagua chuo chako kikuu',
      'tap_refresh_to_load_universities': 'Bonyeza refresh kupakia vyuo vikuu',
      'universities_unavailable_refresh':
          'Vyuo havipatikani. Bonyeza alama ya refresh.',
      'no_universities_available_right_now':
          'Hakuna vyuo vinavyopatikana kwa sasa',
      'please_select_university': 'Tafadhali chagua chuo kikuu',
      'institution': 'Taasisi',
      'search_institution': 'Tafuta taasisi',
      'retry_loading_': 'Jaribu tena kupakia taasisi',
      '_unavailable_refresh': 'Taasisi hazipatikani. Bonyeza alama ya refresh.',
      'no__available_right_now': 'Hakuna taasisi zinazopatikana kwa sasa',
      'please_select_institution': 'Tafadhali chagua taasisi',
      'please_select_institution_from_list':
          'Tafadhali chagua taasisi kutoka kwenye orodha',
      'loading_government_offices': 'Inapakia ofisi za serikali...',
      'retry_loading_government_offices':
          'Jaribu tena kupakia ofisi za serikali',
      'select_government_office': 'Chagua ofisi ya serikali',
      'tap_refresh_to_load_government_offices':
          'Bonyeza refresh kupakia ofisi za serikali',
      'government_offices_unavailable_refresh':
          'Ofisi za serikali hazipatikani. Bonyeza alama ya refresh.',
      'no_government_offices_available_right_now':
          'Hakuna ofisi za serikali zinazopatikana kwa sasa',
      'please_select_government_office': 'Tafadhali chagua ofisi ya serikali',
      'program_course': 'Programu / Kozi',
      'program_required': 'Programu inahitajika',
      'registration_number': 'Namba ya Usajili',
      'registration_number_required': 'Namba ya usajili inahitajika',
      'identification_card': 'Kitambulisho',
      'upload_identification_card': 'Pakia Kitambulisho',
      'upload_identification_hint':
          'Pakia nakala safi ya PDF ya kitambulisho chako. Upeo ni 5MB.',
      'upload_identification_required':
          'Tafadhali pakia kitambulisho kabla ya kuendelea.',
      'university_name': 'Jina la Chuo',
      'university_name_required': 'Jina la chuo linahitajika',
      'college_name': 'Jina la Chuo',
      'college_name_required': 'Jina la chuo linahitajika',
      'institution_name': 'Jina la Taasisi',
      'institution_name_required': 'Jina la taasisi linahitajika',
      'college_reg_no': 'Namba ya Usajili ya Chuo',
      'college_reg_no_required': 'Namba ya usajili ya chuo inahitajika',
      'institution_reg_no': 'Namba ya Usajili ya Taasisi',
      'institution_reg_no_required': 'Namba ya usajili ya taasisi inahitajika',
      'college_email': 'Barua Pepe ya Chuo',
      'college_email_required': 'Barua pepe ya chuo inahitajika',
      'institution_email': 'Barua Pepe ya Taasisi',
      'institution_email_required': 'Barua pepe ya taasisi inahitajika',
      'college_phone': 'Simu ya Chuo',
      'college_phone_required': 'Simu ya chuo inahitajika',
      'institution_phone': 'Simu ya Taasisi',
      'institution_phone_required': 'Simu ya taasisi inahitajika',
      'college_address': 'Anuani ya Chuo',
      'college_address_required': 'Anuani ya chuo inahitajika',
      'institution_address': 'Anuani ya Taasisi',
      'institution_address_required': 'Anuani ya taasisi inahitajika',
      'college_region': 'Mkoa wa Chuo',
      'college_region_required': 'Mkoa wa chuo unahitajika',
      'institution_region': 'Mkoa wa Taasisi',
      'institution_region_required': 'Mkoa wa taasisi unahitajika',
      'select_college_region': 'Chagua mkoa wa chuo',
      'college_district': 'Wilaya ya Chuo',
      'college_district_required': 'Wilaya ya chuo inahitajika',
      'institution_district': 'Wilaya ya Taasisi',
      'institution_district_required': 'Wilaya ya taasisi inahitajika',
      'select_college_district': 'Chagua wilaya ya chuo',
      'select_region_first': 'Chagua mkoa kwanza',
      'college_website': 'Tovuti ya Chuo',
      'institution_website': 'Tovuti ya Taasisi',
      'college_logo': 'Nembo ya Chuo',
      'upload_college_logo': 'Pakia Nembo ya Chuo',
      'upload_college_logo_hint':
          'Pakia nembo safi ya JPG, JPEG, au PNG ya chuo. Upeo ni 5MB.',
      'upload_college_logo_required':
          'Tafadhali pakia nembo ya chuo kabla ya kuendelea.',
      'institution_logo': 'Nembo ya Taasisi',
      'upload_institution_logo': 'Pakia Nembo ya Taasisi',
      'upload_institution_logo_hint':
          'Pakia nembo safi ya JPG, JPEG, au PNG ya taasisi. Upeo ni 5MB.',
      'upload_institution_logo_required':
          'Tafadhali pakia nembo ya taasisi kabla ya kuendelea.',
      'college_type': 'Aina ya Chuo',
      'college_type_required': 'Tafadhali chagua aina ya chuo',
      'institution_type': 'Aina ya Taasisi',
      'institution_type_required': 'Tafadhali chagua aina ya taasisi',
      'coordinator_name': 'Jina la Mratibu',
      'coordinator_name_required': 'Jina la mratibu linahitajika',
      'coordinator_phone': 'Simu ya Mratibu',
      'coordinator_phone_required': 'Simu ya mratibu inahitajika',
      'coordinator_email': 'Barua Pepe ya Mratibu',
      'coordinator_email_required': 'Barua pepe ya mratibu inahitajika',
      'coming_soon': 'Inakuja Karibuni',
      'student_type': 'Aina ya mwanafunzi:',
      'current_student': 'Mwanafunzi wa sasa',
      'expected_graduation_year': 'Mwaka unaotarajiwa kuhitimu',
      'please_select_graduation_year': 'Tafadhali chagua mwaka wa kuhitimu',
      '_type': 'Aina ya mafunzo:',
      'graduation_year': 'Mwaka wa kuhitimu',
      'experience_level': 'Kiwango cha uzoefu',
      'no_experience': 'Hakuna uzoefu',
      'experience_0_1_year': 'Mwaka 0-1',
      'experience_1_2_years': 'Miaka 1-2',
      'experience_2_3_years': 'Miaka 2-3',
      'experience_3_plus_years': 'Miaka 3+',
      'please_select_experience_level': 'Tafadhali chagua kiwango cha uzoefu',
      'organization_name': 'Jina la kampuni',
      'organization_name_required': 'Jina la kampuni linahitajika',
      'search_organization_name': 'Tafuta jina la kampuni',
      'retry_loading_organization_directory':
          'Jaribu tena kupakia orodha ya kampuni',
      'industry': 'Sekta',
      'please_select_industry': 'Tafadhali chagua sekta',
      'organization_size': 'Ukubwa wa kampuni',
      'employees_count': 'Wafanyakazi {size}',
      'please_select_organization_size': 'Tafadhali chagua ukubwa wa kampuni',
      'location': 'Mahali',
      'location_required': 'Mahali panahitajika',
      'organization_description': 'Maelezo ya kampuni',
      'register': 'Jisajili',
      'already_have_account': 'Tayari una akaunti?',
      'website': 'Tovuti',
      'phone': 'Simu',
      'not_provided': 'Haijatolewa',
      'industry_not_set': 'Sekta haijawekwa',
      'edit_profile': 'Hariri Wasifu',
      'edit_job': 'Hariri Kazi',
      'edit_training': 'Hariri Mafunzo',
      'no_organization_description_added_yet':
          'Hakuna maelezo ya kampuni yaliyowekwa bado.',
      'no_deadline': 'Hakuna mwisho wa muda',
      'expired': 'Imeisha muda',
      'days_left': 'Siku {count} zimebaki',
      'closes_today': 'Inafungwa leo',
      'invalid_date': 'Tarehe si sahihi',
      'status_active': 'Ipo wazi',
      'status_closed': 'Imefungwa',
      'salary': 'Mshahara',
      'job_type': 'Aina ya kazi',
      'applicants_count': 'Waombaji {count}',
      'needed_count': 'Wanahitajika {count}',
      'deadline': 'Mwisho wa muda',
      'no_description_provided': 'Hakuna maelezo yaliyowekwa',
      'target_candidates': 'Walengwa',
      'first_year': 'Mwaka wa kwanza',
      'second_year': 'Mwaka wa pili',
      'third_year_plus': 'Mwaka wa tatu na kuendelea',
      'organization_statistics': 'Takwimu za kampuni',
      'total_training': 'Jumla ya kazi',
      'active_training': 'Kazi zilizo wazi',
      'closed_training': 'Kazi zilizofungwa',
      'total_applicants': 'Jumla ya waombaji',
      'average_per_training': 'Wastani kwa mafunzo',
      'average_per_job': 'Wastani kwa kazi',
      'welcome_back': 'Karibu tena,',
      'quick_actions': 'Hatua za haraka',
      'post_training': 'Chapisha Mafunzo',
      'post_job': 'Chapisha kazi',
      'view_training': 'Tazama kazi',
      'find_talent': 'Tafuta vipaji',
      'find_talent_coming_soon': 'Huduma ya kutafuta vipaji inakuja karibuni!',
      'statistics': 'Takwimu',
      'recent_job_postings': 'Kazi zilizochapishwa hivi karibuni',
      'recent_training_postings': 'Kazi zilizochapishwa hivi karibuni',
      'view_all': 'Tazama zote',
      'no_training_posted_yet': 'Bado hakuna kazi zilizochapishwa',
      'click_create_first_job': 'Bonyeza + kuunda kazi yako ya kwanza',
      'details': 'Maelezo',
      'failed_to_load_training': 'Imeshindikana kupakia kazi',
      'untitled_job': 'Kazi isiyo na jina',
      'untitled_training': 'Mafunzo yasiyo na jina',
      'location_not_specified': 'Mahali halijaainishwa',
      'all_applications': 'Maombi yote',
      'this_job': 'Kazi hii',
      'all_organization_applications': 'Maombi yote ya kampuni',
      'applications_for_job': 'Maombi ya {job}',
      'network_error': 'Hitilafu ya mtandao',
      'failed_to_load_applications': 'Imeshindikana kupakia maombi',
      'select_reporting_start_date': 'Chagua tarehe ya kuanza kuripoti',
      'select_reporting_end_date': 'Chagua tarehe ya mwisho ya kuripoti',
      'application_updated_to': 'Ombi limebadilishwa kuwa {status}',
      'failed_to_update_status': 'Imeshindikana kubadili hali',
      'applications_summary': 'Muhtasari wa maombi',
      'total': 'Jumla',
      'shortlisted': 'Walioteuliwa',
      'ed': 'Waliohojiwa',
      'accepted': 'Walikubaliwa',
      'rejected': 'Waliokataliwa',
      'unknown_applicant': 'Mwombaji asiyejulikana',
      'no_email': 'Hakuna barua pepe',
      'selected_job': 'Kazi iliyochaguliwa',
      'selected_training': 'Mafunzo yaliyochaguliwa',
      'university_value': 'Chuo kikuu: {value}',
      'job_value': 'Kazi: {value}',
      'training_value': 'Mafunzo: {value}',
      'shortlist': 'Teua',
      'interview': 'Usaili',
      'accept': 'Kubali',
      'reject': 'Kataa',
      'go_to_my_training': 'Nenda kwenye kazi zangu',
      'no_applications_for_training_yet': 'Bado hakuna maombi kwa kazi zako',
      'no_applications_for_this_job_yet': 'Bado hakuna maombi kwa kazi hii',
      'no_applications_for_this_training_yet':
          'Bado hakuna maombi kwa mafunzo haya',
      'close': 'Funga',
      '_venue': 'Mahali pa usaili',
      'venue_required': 'Mahali panahitajika',
      'venue_hall': 'Ukumbi / Mahali',
      'venue_hint': 'Mfano: Main Hall, Room 4',
      'status_pending': 'Inasubiri',
      'status_shortlisted': 'Walioteuliwa',
      'status_': 'Usaili',
      'status_accepted': 'Imekubaliwa',
      'status_rejected': 'Imekataliwa',
    },
  };

  final SharedPreferencesLoader _preferencesLoader;
  String _localeCode = 'en';

  String get localeCode => _localeCode;
  Locale get locale => Locale(_localeCode);
  String get selectedLanguageName => nativeLanguageName(_localeCode);

  Future<void> _loadSavedLanguage() async {
    final preferences = await _preferencesLoader();
    final savedCode = preferences.getString(_storageKey);
    if (savedCode == null || !_translations.containsKey(savedCode)) {
      return;
    }

    _localeCode = savedCode;
    notifyListeners();
  }

  Future<void> setLocaleCode(String localeCode) async {
    if (!_translations.containsKey(localeCode) || localeCode == _localeCode) {
      return;
    }

    _localeCode = localeCode;
    notifyListeners();

    final preferences = await _preferencesLoader();
    await preferences.setString(_storageKey, localeCode);
  }

  String nativeLanguageName(String localeCode) {
    switch (localeCode) {
      case 'sw':
        return 'Kiswahili';
      case 'en':
      default:
        return 'English';
    }
  }

  String tr(String key, [Map<String, String> params = const {}]) {
    final template =
        _translations[_localeCode]?[key] ?? _translations['en']?[key] ?? key;

    var result = template;
    for (final entry in params.entries) {
      result = result.replaceAll('{${entry.key}}', entry.value);
    }
    return result;
  }
}
